# Generated by Django 2.1.3 on 2019-01-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20181213_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='m_body_material',
            new_name='m_bolting',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='m_body_size',
            new_name='m_bore',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='m_bonnet_bolting_material',
            new_name='m_design',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='m_end_connections',
            new_name='m_end_connection',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='m_rating',
            new_name='m_equipment_type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='m_seat_material',
            new_name='m_operation',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='m_stem_material',
            new_name='m_pressure_rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='m_trim_size',
            new_name='m_size',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='m_trim_type',
            new_name='m_trim_seal',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='m_valve_type',
            new_name='m_vessel_material',
        ),
        migrations.AddField(
            model_name='post',
            name='m_vessel_seal',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
