# Generated by Django 2.1.3 on 2019-01-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_post_m_option_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='m_option_two',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
