# Generated by Django 2.1.5 on 2019-01-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_post_m_option_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='payment',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='shipping',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='shipping_arrangement',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
