# Generated by Django 2.1.5 on 2019-01-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20190109_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping', models.CharField(default='empty', max_length=100)),
                ('shipping_arrangement', models.CharField(default='empty', max_length=100)),
                ('payment', models.CharField(default='empty', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shipping_arrangement',
        ),
    ]
