# Generated by Django 2.1.5 on 2019-01-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_order_shippingmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='shipping',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='empty', max_length=50),
        ),
    ]
