# Generated by Django 2.1.5 on 2019-01-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20190110_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ShippingModel',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='first_name',
            new_name='shipping',
        ),
    ]
