# Generated by Django 2.1.5 on 2019-01-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20190110_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shipping_arr',
            field=models.CharField(default='empty', max_length=50),
        ),
    ]
