# Generated by Django 2.1.5 on 2019-01-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_post_shipping_arr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shipping',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='shipping_arr',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
