# Generated by Django 2.1.5 on 2019-01-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20190110_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deliver',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
